

site_name: API-CARD (PingLab UCLA)

extra_javascript: 
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
    - mdx_math
    
theme:
  name: 'rtd-dropdown'
  highlightjs: true
  hljs_languages: []
  include_homepage_in_sidebar: true
  prev_next_buttons_location: bottom
  navigation_depth: 4
  titles_only: false
  sticky_navigation: true
  collapse_navigation: true
 
 
  
      
markdown_extensions:
  - codehilite:
      linenums: false
      guess_lang: false
      use_pygments: true
      noclasses: true
      pygments_style: manni



nav:
- Home: index.md


- API Card:
  
  - NIH Genomic Data Common: nih-genomic-data-commons.md
  - USCS Genome Browser: ucsc-genome-browser.md
  - Enseble REST API: ensembl-rest-api.md
  - New Gene Info: new-gene-info.md
  - Gene Ontology: gene-ontology.md
  - GWAS Rappid Catalog: gwasrappid-catalog.md
  - OMIM API: omim-api.md
  - Web Gesalt Web API: web-gestalt-web-api.md
  - cBioPortal: cbio-portal.md
  - Scanty : scanty.md
  - PyBio Mart: pybio-mart.md
  - Uniprot API: uniprot.md
  - PubTator Central API: pubtator-central-api.md
  
  


 
 
