

site_name: API-CARD 

extra_javascript: 
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
    - mdx_math
    
theme:
  name: 'rtd-dropdown'
  highlightjs: true
  hljs_languages: []
  include_homepage_in_sidebar: true
  prev_next_buttons_location: bottom
  navigation_depth: 4
  titles_only: false
  sticky_navigation: true
  collapse_navigation: true
 
 
  
      
markdown_extensions:
  - codehilite:
      linenums: false
      guess_lang: false
      use_pygments: true
      noclasses: true
      pygments_style: manni



nav:
- Home: index.md


- API Card:
  
  - NCI Genomic Data Common: nci-genomic-data-commons.md
  - USCS Genome Browser: ucsc-genome-browser.md
  - Ensebl REST API: ensembl-rest-api.md
  - New Gene Info: new-gene-info.md
  - Gene Ontology: gene-ontology.md
  - GWAS Rappid Catalog: gwasrappid-catalog.md
  - OMIM API: omim-api.md
  - WebGesalt Web API: web-gestalt-web-api.md
  - cBio Portal: cbio-portal.md
  - Scanpy : scanty.md
  - PyBio Mart: pybio-mart.md
  - PubTator Central API: pubtator-central-api.md
  - Uniprot API: uniprot.md


- Multiomics Integration:
  
  - Example- Scanpy and  PyBioMart: multiomics-Scanpy_PyBio_Mart.md
  - Example- Scanpy, GO and Uniprot: multiomics-Scanpy_GO_Uniprot.md
  - Example- Scanpy Go: multiomics-Scanpy_GO.md
  - Example- Scanpy, PyBioMart, ScanPy, Go, and Uniprot: multiomics-PyBiomart_Scanpy_GO_Uniprot.md
  - Example- Omim, USGC, GO, Uniprot and DrugBank: multiomics-omim_ucsc_go_Uniprot_DrugBank.md
  - Example- Omim and UCSC: multiomics-omim_ucsc.md
  - Example- NCI, GDC ScanPy and EebGestalt: multiomics-NCI GDC_Scanpy_WebGestalt.md
  - Example- NCI, GDC and GO: multiomics-NCI GDC_GO.md
  - Example- MyGenInfo and cBioportal: multiomics-MyGeneInfo-cBioPortal.md
  - Example- GWAS WebGestalt: multiomics-GWAS_WebGestalt.md
  - Example- GWAS eQTLS: multiomics-GWAS_eQTLs.md
  - Example- Ensembl : multiomics-Ensembl (phenotype annotation-overlap-VEP).md


  
  
  


 
 
